version: "3"
services:
  server:
    build: "./server"
    depends_on:
      - mysql-db
    environment:
      - DB_URI=mysql://root:password@mysql-db/db
    ports:
      - 8100:8100
    volumes:
      - ./server:/opt/app

  mysql-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7
    ports:
      - 0.0.0.0:3306:3306
